audit_header: false
title: Worcester Real Estate Video Blog with Jim Black
description: Our mission at Jim Black Group is to be your best resource for Worcester real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Jim Black Group, your professional Worcester Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Jim Black
  title:
  license_number:
  about_markdown: |
    Jim has been licensed since 2004 and has represented hundreds of buyers and sellers in the Central Mass area. Jim has lived most of his life in Central MA, and is a member of the National, State and Local Board of Realtors. In 2016, Jim was awarded the REALTOR® Choice Award.

    In 2013, Jim founded The Jim Black Group; a full service real estate team specializing in Worcester, MA and the surrounding area. Together, the team provides the highest level of real estate service to their clients. In 2017 Jim's organization partnered with Big Brothers Big Sisters of Central MA with the Closings for Kids campaign. Through this campaign, BBBSCM and the Jim Black Group work closely to raise funds to match waiting kids with prospective Big Brothers and Big Sisters Each month the team donates a portion of the proceeds from every closing to this great cause. You can learn more about and contribute to this campaign <href="https://bbbscm.org/closings-for-kids" target="_blank">here</a>
  brand: Jim Black Group
  brokerage: Keller Williams Pinnacle Central
  market: Worcester
  address: 60 Shrewsbury Street, 2nd Floor Worcester, MA 01604
  phone: 508-365-3532
  phone_type:
  phone2:
  phone2_type:
  email: results@jimblackgroup.com
  url: http://jimblacksellshomes.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.jimblacksellshomes.com/home_value
  second_CTA_text: Home Search
  second_CTA_URL: https://www.jimblacksellshomes.com/search#?q_limit=36&q_prioritize=agents.0.id=TM305063|office.id=K95491&mlsId=7&status=1|3&q_sort=createdAt-&q_offset=0

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Worcester Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.jimblacksellshomes.com/home_value

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Worcester Home?"
    CTA_text2: "Search the entire MLS for your Worcester home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.jimblacksellshomes.com/search#?q_limit=36&q_prioritize=agents.0.id=TM305063|office.id=K95491&mlsId=7&status=1|3&q_sort=createdAt-&q_offset=0

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/JimBlackGroup/
  linkedin_url: https://www.linkedin.com/company/jimblackgroup/
  youtube_url: https://www.youtube.com/channel/UCRJPjyOPD4acgozlvsIvTZw
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Worcester Real Estate Podcast with Jim Black'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Worcester Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Jim Black Group - your professional Worcester Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Worcester, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Jim Black'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Worcester Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#88171b'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
